export { default as Login } from './Login'
export { default as Error } from './Error'
export { default as SignUp } from './SignUp'
export { default as MainPage } from './MainPage'
export { default as PostDetail } from './PostDetail'
export { default as CreatePost } from './CreatePost'
